package it.polimi.ingsw.server.controller;

/**
 * A class representing all the states of the game
 */
public enum StateType {

    CHANGE_PLAYER_STATE,
    SET_PLAYER_PARAMETER_STATE,
    PLAY_ASSISTANT_STATE,
    MOVE_STUDENT_STATE,
    MOVE_MOTHER_NATURE_STATE,
    CHOOSE_CLOUD_STATE,
    END_STATE,
    USE_CHARACTER_CARD1_STATE,
    USE_CHARACTER_CARD4_STATE,
    USE_CHARACTER_CARD5_STATE,
    USE_CHARACTER_CARD8_STATE,
    USE_CHARACTER_CARD9_STATE,
    USE_CHARACTER_CARD10_STATE,
    USE_CHARACTER_CARD11_STATE,
    USE_CHARACTER_CARD12_STATE

}
